# Generated by Django 5.0.7 on 2024-08-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgritechConnect', '0002_alter_farmer_groups_alter_farmer_password_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='username',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='farmer_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='farmer_permissions_set', to='auth.permission'),
        ),
    ]
